In [16]:
from selenium import webdriver #controlar o navegador
from selenium.webdriver.common.keys import Keys # usar o teclado
from selenium.webdriver.common.by import By # localizar os itens no computador

#criar navegador
navegador = webdriver.Chrome('C:/Users/Dan/Desktop/Python/Intensivao/chromedriver.exe')


#entrar no google e pesquisar no google "cotação do dolar"
navegador.get("https://www.google.com.br/")
navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar") #qual parametro quero usar e qual parametro
navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

#copiar cotação do dolar
cotacao_dolar = navegador.find_element(By.XPATH, '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')

print(cotacao_dolar)

#pesquisar cotação do euro
navegador.get("https://www.google.com.br/")
navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação euro") #qual parametro quero usar e qual parametro
navegador.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

#copiar cotação do euro
cotacao_euro = navegador.find_element(By.XPATH, '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')
print(cotacao_euro)

#entrar no site de ouro
navegador.get("https://www.melhorcambio.com/ouro-hoje")

#copiar cotação do ouro
cotacao_ouro = navegador.find_element(By.XPATH, '//*[@id="comercial"]').get_attribute('value')
print(cotacao_ouro)

cotacao_ouro = cotacao_ouro.replace(",",".")

navegador.quit()

C:\Users\Dan\AppData\Local\Temp/ipykernel_53260/2535314703.py:6: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  navegador = webdriver.Chrome('C:/Users/Dan/Desktop/Python/Intensivao/chromedriver.exe')

5.0129
5.539630467
321,79

In [7]:
#importart a base de dados
import pandas as pd

tabela = pd.read_excel("Produtos.xlsx")
display(tabela)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

In [18]:
#atualizar as cotações na base de dados
tabela.loc[tabela["Moeda"]=="Dólar", "Cotação"] = float(cotacao_dolar)

tabela.loc[tabela["Moeda"]=="Euro", "Cotação"] = float(cotacao_euro)

tabela.loc[tabela["Moeda"]=="Ouro", "Cotação"] = float(cotacao_ouro)

#atualizar os preços de compra e de vendas na base de dados
#preco de compra = preco original * cotacao
tabela["Preço de Compra"] = tabela["Preço Original"] + tabela["Cotação"]
#preco de venda = preco de compra * margem
tabela["Preço de Venda"] = tabela["Preço de Compra"] + tabela["Margem"]



display(tabela)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.01290,1005.00290,1.40,1006.40290
1,Carro Renault,4500.00,Euro,5.53963,4505.53963,2.00,4507.53963
2,Notebook Dell,899.99,Dólar,5.01290,905.00290,1.70,906.70290
3,IPhone,799.00,Dólar,5.01290,804.01290,1.70,805.71290
4,Carro Fiat,3000.00,Euro,5.53963,3005.53963,1.90,3007.43963
5,Celular Xiaomi,480.48,Dólar,5.01290,485.49290,2.00,487.49290
6,Joia 20g,20.00,Ouro,321.79000,341.79000,1.15,342.94000

In [20]:
#Exportar essa base de dados para resultado atualizado
tabela.to_excel("Produtos.xlsx", index=False)